openapi: 3.0.0
info:
  version: v1
  title: My API
paths:
  /api/ticket/booking:
    post:
      tags:
        - QuanLyDatVe
      operationId: DatVe
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: DanhSachVe
          in: body
          required: false
          schema:
            $ref: "#/definitions/DanhSachVeDat"
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/ticket/getShowTime:
    get:
      tags:
        - QuanLyDatVe
      operationId: LayDanhSachPhongVe
      consumes: []
      produces: []
      parameters:
        - name: showTimeId
          in: query
          required: false
      responses:
        "200":
          description: Success
  /api/ticket/createShowTime:
    post:
      tags:
        - QuanLyDatVe
      operationId: TaoLichChieu
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: lich
          in: body
          required: false
          schema:
            $ref: "#/definitions/LichChieuInsert"
        - name: Authorization
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/author/login:
    post:
      tags:
        - QuanLyNguoiDung
      operationId: DangNhap
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: user
          in: body
          required: false
          schema:
            $ref: "#/definitions/ThongTinDangNhapVM"
      responses:
        "200":
          description: Success
  /api/author/register:
    post:
      tags:
        - QuanLyNguoiDung
      operationId: register
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: newUser
          in: body
          required: false
          schema:
            $ref: "#/definitions/newUser"
      responses:
        "200":
          description: Success
  /api/user/getUser:
    get:
      tags:
        - QuanLyNguoiDung
      operationId: LayDanhSachNguoiDung
      consumes: []
      produces: []
      parameters:
        - name: AccessToken
          in: header
          required: true
          type: string
          default: ""
      responses:
        "200":
          description: Success
  /api/user/paginationUserList:
    get:
      tags:
        - QuanLyNguoiDung
      operationId: LayDanhSachNguoiDungPhanTrang
      consumes: []
      produces: []
      parameters:
        - name: page
          in: query
          required: false
          type: integer
          format: int32
          default: 1
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
          default: 20
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/user/searchUser:
    post:
      tags:
        - QuanLyNguoiDung
      operationId: TimKiemNguoiDung
      consumes: []
      produces: []
      parameters:
        - name: userName
          in: query
          required: false
          type: string
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/user/getUserByUserName:
    get:
      tags:
        - QuanLyNguoiDung
      operationId: ThongTinTaiKhoan
      consumes: []
      produces: []
      parameters:
        - name: findUserName
          in: query
          required: true
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/user/createUser:
    post:
      tags:
        - QuanLyNguoiDung
      operationId: ThemNguoiDung
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: newUser
          in: body
          required: false
          schema:
            $ref: "#/definitions/NguoiDungVM"
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/user/updateUserByUsername:
    put:
      tags:
        - QuanLyNguoiDung
      operationId: CapNhatThongTinNguoiDung
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: newUserUpdate
          in: body
          required: false
          schema:
            $ref: "#/definitions/NguoiDungVM"
        - name: Authorization
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/user/avatar:
    post:
      tags:
        - QuanLyNguoiDung
      operationId: AvatarUser
      consumes:
        - multipart/form-data
      parameters:
        - name: avatar
          in: formData
          required: false
          type: file
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/user/deleteUser:
    delete:
      tags:
        - QuanLyNguoiDung
      operationId: XoaNguoiDung
      consumes: []
      produces: []
      parameters:
        - name: findUserName
          in: query
          required: false
          type: string
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/movie/getListMovie:
    get:
      tags:
        - QuanLyPhim
      operationId: LayDanhSachPhim
      consumes: []
      produces: []
      parameters:
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/movie/paginationMovieList:
    get:
      tags:
        - QuanLyPhim
      operationId: LayDanhSachPhimPhanTrang
      consumes: []
      produces: []
      parameters:
        - name: page
          in: query
          required: false
          type: integer
          format: int32
          default: 1
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: Success
  /api/movie/createMovie:
    post:
      tags:
        - QuanLyPhim
      operationId: ThemPhimUploadHinh
      consumes:
        - multipart/form-data
      parameters:
        - name: name
          in: formData
          required: true
          type: string
        - name: startDate
          in: formData
          required: true
          type: string
        - name: time
          in: formData
          required: true
          type: string
        - name: evaluate
          in: formData
          required: true
          type: integer
        - name: poster
          in: formData
          required: true
          type: file
        - name: banner
          in: formData
          required: true
          type: file
        - name: trailer
          in: formData
          required: true
          type: string
        - name: AccessToken
          in: header
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/movie/updateMovie:
    put:
      tags:
        - QuanLyPhim
      operationId: CapNhatPhimUpload
      consumes:
        - multipart/form-data
      parameters:
        - name: movieId
          in: query
          required: true
          type: integer
        - name: name
          in: formData
          required: true
          type: string
        - name: startDate
          in: formData
          required: true
          type: string
        - name: time
          in: formData
          required: true
          type: string
        - name: evaluate
          in: formData
          required: true
          type: integer
        - name: poster
          in: formData
          required: true
          type: file
        - name: banner
          in: formData
          required: true
          type: file
        - name: trailer
          in: formData
          required: true
          type: string
        - name: AccessToken
          in: header
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/movie/deleteMovie:
    delete:
      tags:
        - QuanLyPhim
      operationId: XoaPhim
      consumes: []
      produces: []
      parameters:
        - name: movieId
          in: query
          required: false
          type: integer
          format: int32
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  /api/movie/getMovieById:
    get:
      tags:
        - QuanLyPhim
      operationId: LayThongTinPhim
      consumes: []
      produces: []
      parameters:
        - name: movieId
          in: query
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: Success
  /api/cinema/getCinemaById:
    get:
      tags:
        - QuanLyRap
      operationId: LayThongTinHeThongRap
      consumes: []
      produces: []
      parameters:
        - name: cinemaId
          in: query
          required: false
          type: string
          default: ""
      responses:
        "200":
          description: Success
  /api/cinema/getInfoCineplex:
    get:
      tags:
        - QuanLyRap
      operationId: LayThongTinCumRapTheoHeThong
      consumes: []
      produces: []
      parameters:
        - name: cineplexId
          in: query
          required: false
          type: string
          default: ""
      responses:
        "200":
          description: Success
  /api/cinema/getMovieListFromCinema:
    get:
      tags:
        - QuanLyRap
      operationId: LayThongTinLichChieuPhim
      consumes: []
      produces: []
      parameters:
        - name: cinemaId
          in: query
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: Success
definitions:
  DanhSachVeDat:
    type: object
    properties:
      showtimeId:
        format: int32
        type: integer
      seatId:
        uniqueItems: false
        type: array
        items:
          $ref: "#/definitions/VeVM"
  VeVM:
    type: string
  LichChieuInsert:
    type: object
    properties:
      cinemaId:
        format: int32
        type: integer
      movieId:
        format: int32
        type: integer
      startTime:
        type: string
  ThongTinDangNhapVM:
    type: object
    properties:
      userName:
        type: string
      password:
        type: string
  newUser:
    type: string
    properties:
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      password:
        type: string
  NguoiDungVM:
    type: object
    properties:
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      password:
        type: string
      role:
        type: string
      avatar:
        type: string
  "KeyValuePair[String,StringValues]":
    type: object
    properties:
      key:
        type: string
        readOnly: true
      value:
        uniqueItems: false
        type: array
        items:
          type: string
        readOnly: true
