swagger: "2.0"
info:
  version: v1
  title: My API
paths:
  "/api/ticket/booking":
    post:
      tags:
        - QuanLyDatVe
      operationId: DatVe
      consumes:
        - application/json-patch+json
        - json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: DanhSachVe
          in: body
          required: false
          schema:
            "$ref": "#/definitions/DanhSachVeDat"
        - name: token
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/ticket/getShowTime":
    get:
      tags:
        - QuanLyDatVe
      operationId: LayDanhSachPhongVe
      consumes: []
      produces: []
      parameters:
        - name: showTimeId
          in: query
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: Success
  "/api/ticket/createShowTime":
    post:
      tags:
        - QuanLyDatVe
      operationId: TaoLichChieu
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: lich
          in: body
          required: false
          schema:
            "$ref": "#/definitions/LichChieuInsert"
        - name: Authorization
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/author/login":
    post:
      tags:
        - QuanLyNguoiDung
      operationId: DangNhap
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: user
          in: body
          required: false
          schema:
            "$ref": "#/definitions/ThongTinDangNhapVM"
      responses:
        "200":
          description: Success
  "/api/author/register":
    post:
      tags:
        - QuanLyNguoiDung
      operationId: DangKy
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: user
          in: body
          required: false
          schema:
            "$ref": "#/definitions/newUser"
      responses:
        "200":
          description: Success
  "/api/user/getUser":
    get:
      tags:
        - QuanLyNguoiDung
      operationId: LayDanhSachNguoiDung
      consumes: []
      produces: []
      parameters:
        - name: AccessToken
          in: header
          required: true
          type: string
          default: ""
      responses:
        "200":
          description: Success
  "/api/user/paginationUserList":
    get:
      tags:
        - QuanLyNguoiDung
      operationId: LayDanhSachNguoiDungPhanTrang
      consumes: []
      produces: []
      parameters:
        - name: page
          in: query
          required: false
          type: integer
          format: int32
          default: 1
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
          default: 20
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/user/searchUser":
    post:
      tags:
        - QuanLyNguoiDung
      operationId: TimKiemNguoiDung
      consumes: []
      produces: []
      parameters:
        - name: userName
          in: query
          required: false
          type: string
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/user/getUserByUserName":
    post:
      tags:
        - QuanLyNguoiDung
      operationId: ThongTinTaiKhoan
      consumes: []
      produces: []
      parameters:
        - name: findUserName
          in: query
          required: true
          # type: string
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/user/createUser":
    post:
      tags:
        - QuanLyNguoiDung
      operationId: ThemNguoiDung
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: newUser
          in: body
          required: false
          schema:
            "$ref": "#/definitions/NguoiDungVM"
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/user/updateUserByUsername":
    put:
      tags:
        - QuanLyNguoiDung
      operationId: CapNhatThongTinNguoiDung
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: nd
          in: body
          required: false
          schema:
            "$ref": "#/definitions/NguoiDungVM"
        - name: Authorization
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
    post:
      tags:
        - QuanLyNguoiDung
      operationId: CapNhat
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: nd
          in: body
          required: false
          schema:
            "$ref": "#/definitions/NguoiDungVM"
        - name: Authorization
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/user/deleteUser":
    delete:
      tags:
        - QuanLyNguoiDung
      operationId: XoaNguoiDung
      consumes: []
      produces: []
      parameters:
        - name: findUserName
          in: query
          required: false
          type: string
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/movie/getListMovie":
    get:
      tags:
        - QuanLyPhim
      operationId: LayDanhSachPhim
      consumes: []
      produces: []
      parameters:
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/movie/paginationMovieList":
    get:
      tags:
        - QuanLyPhim
      operationId: LayDanhSachPhimPhanTrang
      consumes: []
      produces: []
      parameters:
        - name: page
          in: query
          required: false
          type: integer
          format: int32
          default: 1
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: Success
  "/api/movie/createMovie":
    post:
      tags:
        - QuanLyPhim
      operationId: ThemPhimUploadHinh
      consumes:
        - multipart/form-data
      produces: []
      parameters:
        - name: frm
          in: formData
          required: false
          type: array
          items: {}
          collectionFormat: multi
          uniqueItems: false
      responses:
        "200":
          description: Success
  "/api/movie/updateMove":
    post:
      tags:
        - QuanLyPhim
      operationId: CapNhatPhimUpload
      consumes:
        - multipart/form-data
      produces: []
      parameters:
        - name: movieId
          in: query
          required: true
          type: string
        - name: fileUpload
          in: formData
          required: false
          type: file
        - name: dataMovie
          in: formData
          required: false
          type: array
          items: {}
          collectionFormat: multi
          uniqueItems: false
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/movie/deleteMovie":
    delete:
      tags:
        - QuanLyPhim
      operationId: XoaPhim
      consumes: []
      produces: []
      parameters:
        - name: movieId
          in: query
          required: false
          type: integer
          format: int32
        - name: AccessToken
          in: header
          description: access token
          required: true
          type: string
      responses:
        "200":
          description: Success
  "/api/movie/getMovieById":
    get:
      tags:
        - QuanLyPhim
      operationId: LayThongTinPhim
      consumes: []
      produces: []
      parameters:
        - name: movieId
          in: query
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: Success
  "/api/cinema/getCinemaById":
    get:
      tags:
        - QuanLyRap
      operationId: LayThongTinHeThongRap
      consumes: []
      produces: []
      parameters:
        - name: cinemaId
          in: query
          required: false
          type: string
          default: ""
      responses:
        "200":
          description: Success
  "/api/cinema/getInfoCineplex":
    get:
      tags:
        - QuanLyRap
      operationId: LayThongTinCumRapTheoHeThong
      consumes: []
      produces: []
      parameters:
        - name: cineplexId
          in: query
          required: false
          type: string
          default: ""
      responses:
        "200":
          description: Success
  "/api/cinema/LayThongTinLichChieuHeThongRap":
    get:
      tags:
        - QuanLyRap
      operationId: LayThongTinLichChieuHeThongRap
      consumes: []
      produces: []
      parameters:
        - name: maHeThongRap
          in: query
          required: false
          type: string
          default: ""
        - name: maNhom
          in: query
          required: false
          type: string
          default: GP01
      responses:
        "200":
          description: Success
  "/api/cinema/getMovieListFromCinema":
    get:
      tags:
        - QuanLyRap
      operationId: LayThongTinLichChieuPhim
      consumes: []
      produces: []
      parameters:
        - name: cinemaId
          in: query
          required: false
          type: integer
          format: int32
          default: 0
      responses:
        "200":
          description: Success
definitions:
  DanhSachVeDat:
    type: object
    properties:
      showtimeId:
        format: int32
        type: integer
      seatId:
        uniqueItems: false
        type: array
        items:
          "$ref": "#/definitions/VeVM"
  VeVM:
    type: string
  LichChieuInsert:
    type: object
    properties:
      maPhim:
        format: int32
        type: integer
      ngayChieuGioChieu:
        type: string
      maRap:
        type: string
      giaVe:
        format: double
        type: number
  ThongTinDangNhapVM:
    type: object
    properties:
      userName:
        type: string
      password:
        type: string
  newUser:
    type: object
    properties:
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      password:
        type: string
  NguoiDungVM:
    type: object
    properties:
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      password:
        type: string
      role:
        type: string
      avatar:
        type: string
  KeyValuePair[String,StringValues]:
    type: object
    properties:
      key:
        type: string
        readOnly: true
      value:
        uniqueItems: false
        type: array
        items:
          type: string
        readOnly: true
